var self = module.exports = {
    Mongouri: "mongodb://localhost:27017/",
    collection1: "Process1",
    collection2: 'Process2',
    servers: ['http://54.200.197.244',
        'http://18.236.115.136',
        'http://54.203.40.148',
        'http://54.202.49.163',
        'http://18.237.55.112',
        'http://54.149.219.241',
        'http://34.219.100.42',
        'http://34.212.225.220',
        'http://34.211.111.125',
        'http://52.25.57.11',
        'http://54.245.198.13',
        'http://34.221.197.229',
        'http://34.213.202.15',
        'http://35.164.167.118',
        'http://52.12.155.73',
        'http://35.165.229.169',
        'http://34.221.245.60',
        'http://54.244.42.83',
        'http://34.220.255.214',
        'http://35.160.148.43'
    ],

    nextButtonSelectors: [
        '//li/a[@class="paginateLast"]',
        "//div[@id='jobs-main']/div[1]/div[2]/span[2]/button[3]",
        "//input[@id='cphBody_btnPageNext']",
        '//li[@class="next_link arrow_links"]/a',
        '//a/span[@class="css-6s8faq e1wiielh4"]',
        "//a[@class='jp-next']",
        '//a[@id="next"]',
        "//a[@onclick='listPagination(next)']",
        '//input[@class="pagebuttonnext"]',
        '//a[@class="next page-numbers"]',
        "//div[@id='content']/div/p[1]/a[@class='paginationItem ']",
        "//div[@class='sf-c-pagination']/a[@name='btn-next']",
        "//div[@class='jobs_pagination_main']/div[1]/ul/li[8]/a",
        "//button[@class='mat-paginator-navigation-next mat-icon-button']",
        "//a[@class='next']",
        "//div[@class='right_content']/p[22]//a",
        "//a[@id='showMoreJobs']",
        "//input[@id='__Next']",
        "//span[@class='jtable-page-number-next ui-button ui-state-default']",
        '//input[@name="ctl00$cphBody$btnPageNext"]',
        "//div[@id='search-results']/div/div[1]//a[@class='page-nav next']",
        '//div[@class="row footer"]/div[3]/input',
        '//a[@class="next"]',
        '//input[@id="cphBody_btnPageNext"]',
        '//section[@class="jr-row jr-th jr-sel"]//a[@title="Next"]',
        '//a[@class="next"]',
        '//input[@id="__Next" and not(contains(@disabled,"disabled"))]',
        '//input[@id="cphBody_btnPageNext"]',
        '//button[@class="next hireology-button btn hireology-button--medium hireology-button--outline"]',
        "//input[contains(@onclick,'submitNextPage')]",
        '//a[@class="showMoreJobs UnderLineLink ng-binding"]',
        '//a[@class="jv-pagination-next"]',
        "//div[@class='centerbox-results']/form/h3[1]/span[@class='small-results']/a",
        '//a[@class="sf-c-arrow-btn btn btn-default right-arrow"]',
        '//a[@class="searchresultlist__paging__link searchresultlist__paging__link--right "]',
        '//div[@class="e961-9 x-column x-sm x-1-3"]/a',
        '//a[@id="joblist_next"]',
        "//div[@id='divR1']/div/div/table/tbody/tr[23]//a",
        "//div[@class='pagination paging-btm']/a[2]",
        "//div[@class='jobs-container']/div[1]/div[2]/div/a[@class='jp-next']",
        '//div[@class="ats_pagination_block"]/a[@id="j_id0:j_id1:atsForm:j_id152"]',
        '//button[@class="next hireology-button btn hireology-button--medium hireology-button--outline"]',
        '//button[@id="Jobs_PagedJobList_NextLink"]',
        "//div[@id='layout_content']/div[2]/div[1]/ul/li[@class='pagination_next']",
        '//div[@id="ctl00_ContentPlaceHolder1_pnlResults"]//table//a[@id="ctl00_ContentPlaceHolder1_grdOpenJobs_ctl01_btnNext"]',
        '//div[@class="pageContent"]/div/div[2]/div[2]//a[@id="textLink"]',
        '//li[@class="next"]',
        '//button[@class="mat-paginator-navigation-next mat-icon-button"]',
        "//html//body//form/table[3]/tbody/tr[13]/td/a",
        '//div[@class="pagination-next"]/a',
        "//a[@id='40:_next']",
        "//span[@class='current next']",
        "//li[@class='next']/a",
        '//div[@class="bottomPagerbar clearfix"]//div[@class="pages"]/a[@id="JobSearchResults:j_id137:j_id138:enhancedSearch:j_id231"]',
        "//div[@class='pagination-container']/ul/li[1]/a",
        '//a[@class="paginate_disabled_next"]',
        "//li[@class='next']",
        '//a[@class="PHPLinkPagination nextbtn"]',
        '//div[@class="pagination mobile"]/a[@class="next pagination-button "]',
        "//a[@id='next-page']",
        "//li[@class='pager-next last']/a",
        "//a[@class='next tracking-added active']",
        "//div[@id='main-content']/div[2]/div/table/tbody/tr[3]/td/table/tbody/tr[3]//input[@title='Next Page']",
        "//td[@id='ATSPageNext']/a",
        "//div[@class='pagingPanel']/a[1]",
        '//a[@class="next pagination-button "]',
        '//a[@class="page-link"] /span[contains(text(), "›")]',
        '//a[@class="page-link"] /span[contains(text(), "Next")]',
        "//a[@id='psjobstable_next']",
        "//a[@id='joblist_next']",
        '//div[@id="jobListSummary"]/div[4]/input',
        '//a[@class="prev-next hidden-phone"]',
        '//a[@aria-label="Next Page"]',
        '//div[@class="pager"]/a[@class="pager-next"]',
        '//li[@class="pagination-next page-item"]/a[@class="page-link"]',
        '//a[@aria-label="Go to Next Page"]',
        '//a[@class="showMoreJobs UnderLineLink ng-binding"]',
        '//div[@id="pager_container"]/a[@class="SMALLFONTBold"]',
        '//input[@id="cphBody_btnPageNext"]',
        '//a[@class="pagination-item-link pagination-item-link--next"]',
        '//button[@class="next hireology-button btn hireology-button--medium hireology-button--outline"]',
        '//td[@class="resultsHeaderPaginator"]//div/ul/li[@class="sfPaginatorArrowContainer paginationArrowContainer next"]/a',
        '//span[@class="current next"]',
        '//a[@class="next"]',
        '//a[@ng-click="setPage(currentPage + 1)"]',
        '//a[@class="next page-numbers"]',
        '//li[@class="next"]/a',
        '//div[@class="bottomPagerbar clearfix"]/div/a[@title="Next"]',
        '//div[@class="ats_pagination_block"]//a[3]',
        '//ul[@class="pagination"]//a[@id="pagination1"]',
        '//a[@class="PHPLinkPagination nextbtn"]',
        '//a[@id="nextButton"]',
        '//div[@id="ctl00_ctl00_ContentContainer_mainContent_ctl00_VacancyPager2"]//a[8]',
        '//div[@class="pagination pagination--bottom clearfix"]/a[5]',
        '//a[@id="next-page"]',
        '//a[@title="Go to next page"]',
        '//a[@title="Go To Next Page"]',
        '//a[@title="Next page"]',
        '//a[@title="Next"]',
        '//a[@aria-label="Next"]',
        '//a[@id="next"]',
        '//a[@class="next_page"]',
        '//a[@class="paginate_button next"]',
        '//i[@class="page-next fa fa-angle-right"]',
        '//a[@aria-label="Next »"]',
        '//button[@class="btn btn-outline next"]',
        '//a[@id="psjobstable_next"]',
        '//button[@aria-label="Next page"]',
        '//a[@id="NextPageArrow"]',
        '//div[@class="paging__pages"]/button[@class="page"]',
        '//a[@class="next-page-caret"]',
        '//i[@class="fa fa-arrow-right"]',
        '//a[@class="paginate_enabled_next"]',
        '//li[@class="pager__item pager__item--next"]/a',
        '//li[@class="jrp-desktop-next-page-element"]/a',
        '//a[@class="next tracking-added active"]',
        '//a[@class="paginate_disabled_next"]',
        '//a[@class="next pagination-button "]',
        'input[class="pagination-current"]',
        '//a[@class="h-padding-large next-button-link"]',
        'span[aria-label=\"Next page\"]',
        '//div[@class="page"]/input[@id="page_"]',
        '//div[@class="k-pager-wrap k-grid-pager k-widget k-floatwrap"]/a[@title="Next"]',
        '//div[@class="jobInfo"]',
        '//a[@class="page-link next"]',
        '//div[@class="careers-welcome"]/ol[@class="H2L2-ol"]/li',
        '//span[@id="direct_moreLessLinks_listingDiv"]',
        '//div[@class="more-button"]/a[@class="button load-more-jobs"]',
        '//tr[@class="data-row clickable"]',
        '//a[@class="jv-pagination-next"]',
        '//a[@aria-label="Go to the next page of results."]',
        '//a[@class="rh-pager__link--arrow"]',
        '//button[@class="pagination--page pagination--next"]',
        '//section/div/a[@class="next"]',
        '//a[@aria-label="next"]',
        '//div[@class="pagination"]//li/a/i[@class="icon-angle-right"]',
        "//a[contains(text(), 'next')]",
        '//div[@class="pagerpanel"]/span/span/a[@id="next"]',
        '//div[@class="yui-pg-container"]/a[@class="yui-pg-next"]',
        '//a/span[@class="ui-icon ui-icon-circle-arrow-e"]',
        '//div[@class="pagingButtons"]/a[@class="normalanchor ajaxable scroller scroller_movenext buttonEnabled"]',
        '//div[@class="pagination-paging"]/a[@class="next"]',
        '//div[@id="tm_paging"]/span/div/a[@class="next_page"]',
        '//section[@id="content-main"]/div/section/section[3]/div[2]/a',
        '//div[@id="jobListingList"]/nav/ul/li[9]/a',
        "//span/a[contains(text(), 'Next')]",
        '//li/a[@title="Go to next page"]',
        '//div[@class="pager"]/a[@class="pager-next-arrow"]',
        '//ul[@class="pager"]/li/a[@class="pageSelector"]',
        '//span[@title="Next page of results"]',
        "//button[contains(text(), 'Next')]",
        "//span[contains(text(), 'Next')]",
        '//a[@class=\"paginationItemLast\"]',
        '//a[@aria-label="View Next page"]',
        '//a[contains(text(), ">")]',
        '//a[contains(text(), "»")]',
        '//a[contains(text(), ">>")]',
        "//a[contains(text(), 'Next Page')]",
        "//span[contains(text(), 'Next Page')]",
        "//a[contains(., 'NEXT')]",
        "//a[contains(., 'Next')]",
        '//a[@title="Go to next Jobs page"]',
        '//span[contains(text(), ">")]',
        '//span[contains(text(), "›")]',
        '//a[contains(text(), " Additional Job Postings")]'
    ],
    loadMoreSelector: [
        '//button[@class="btn-default btn deafult"]/descendant::span[1]',
        '//a[@class="load_more_jobs" and not(contains(@style,"display: none"))]',
        '//h5[contains(@data-bind,"visible") and not(contains(@style,"display: none"))]/descendant::a[1]',
        '//button[@class="btn btn-outline-primary btn-block"]',
        '//p[@class="load-more-data ng-binding" and not(contains(@style,"display: none"))]',
        '//a[@class="awsm-load-more awsm-load-more-btn"]',
        '//div[@id="recent-jobs"]//a[@class="more-link button"]',
        '//button[@class="btn-default btn deafult"]',
        '//button[@class="btn-default btn deafult"]',
        "//a[@id='LoadMoreJobs']",
        "//button[@id='tile-more-results']",
        "//button[@class='btn btn-outline-primary']",
        "//p[@class='load-more-data ng-binding']",
        "//a[@class='load_more_jobs']",
        "//a[@id='load-more']",
        "//li[@class='pager__item']/a",
        '//div[@id="recent-jobs"]/p/a[@class="more-link button"]',
        "//a[@id='button_moreJobs']",
        '//button[@class="alm-load-more-btn more"]',
        '//button[@class="overview-container__showmore"]',
        "//button[@class='more']",
        '//a[@class="load_more_jobs"]',
        '//a[@id="button_moreJobs"]',
        '//button[@class="btn btn-default btn-block search-card-container__btn-load-more w-100"]',
        "//button[@class='btn btn-outline-primary btn-block']",
        "//button[@id='load-more']",
        '//a[@id="load-more"]',
        "//div[@id='bottomBranding']/div[1]/p/a",
        '//a[@class="next-posts-link load_more_jobs"]',
        "//a[@id='loadMore']",
        "//button[@class='button-red button-expand js-trigger-expand see-more-insights']",
        "//div[@class='btn']",
        "//span[@class='button lazy']",
        "//input[@id='loadMoreButton']",
        '//a[@aria-label="Go to Next Page"]',
        '//div[@id="Opportunities"]/div[4]/div/h5/a[@id="LoadMoreJobs"]',
        '//div[@class="blog-pagination1"]/a[@class="next-posts-link load_more_jobs"]',
        '//div[@id="listings"]/span/div/button',
        '//div[@class="searchResults"]//input[@class="button"]',
        '//button[@class="btn btn-outline-primary btn-block"]',
        '//div[@class="center bloc"]/a[@class="btn btn-clear btn-clear-blue b-i"]',
        '//div[@class="jobs-btn-wrap"]/button',
        '//div[@class="JobPagerButton"]/div/a[@class="primaryButton"]',
        '//div[@id="careers"]/a[@id="load-more"]',
        '//div[@id="bottomBranding"]/div[1]/p/a[@class="view-all-health"]',
        '//a[@id="LoadMoreJobs"]',
        '//span[@class="loadMore"]',
        '//a[@class="button-secondary button-secondary--red job-board__job-list__load-more"]',
        '//li[@class="pager-show-more-next first last"]/a',
        '//a[@class="load_more_jobs"]/strong',
        '//div[@id="show-more-button"]/a',
        '//div[@id="load-jobs-btn"]/a/button',
        '//a[@class="c-button js-filter-careers"]',
        '//p[@class="load-more-data ng-binding"]',
        '//div[@class="job_listings"]/a[@class="load_more_jobs"]',
        '//a[@title="More Jobs"]',
        '//input[@class="button"]',
        "//span[contains(text(), 'Load More')]",
        "//button[contains(text(), 'LOAD MORE')]",
        "//a[contains(text(), 'Load More')]",
        "//a[contains(text(), 'Show More')]",
        "//span[contains(text(), 'Show More')]",
        // "//a[contains(text(), 'More')]",
        // "//a[contains(text(), 'Load')]",
    ],
    exceptionDomain: ['nescoresource.com', 'www.merraine.com', 'www.huxley.com', 'www.realstaffing.com', 'jobs.netflix.com', 'prestigehealthcare.vikus.net', 'www.progressiverecruitment.com', 'nexionhealth.vikus.net', 'karriere.fresenius.de', 'sites.hireology.com', 'www.tscti.com', 'www1.jobdiva.com', 'www.governmentjobs.com', 'careers.precast.com', 'www.pike.com', 'usatodaynetworkcareers.com', 'www.snyderslance.com'],
    URL: require('url'),

}